# Generated by Django 2.2.2 on 2020-10-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filedetails',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='my_files/')),
            ],
        ),
    ]
